### ISSUE TITLE
Loading tobii DLL failed

### ISSUE THREAD

**Issue by deinhofer** [mh-salari/tobii_recorder#1]
I have installed python3.10 64 bit on a Windows 11 machine with Tobii_Eye_Tracking_Core_v2.13.1.7294_x86.exe.

Then I have installed tobii_recorder and pandas packages.

When trying to execute the example.py program I get the following error message:

```
ImportError: DLL load failed while importing tobii: Das angegebene Modul wurde nicht gefunden.
(.venv) PS C:\Users\deinh\PycharmProjects\test-tobii-python> python.exe .\main.py
Traceback (most recent call last):
  File "C:\Users\deinh\PycharmProjects\test-tobii-python\main.py", line 11, in <module>
    import tobii_recorder
  File "C:\Users\deinh\PycharmProjects\test-tobii-python\.venv\lib\site-packages\tobii_recorder\__init__.py", line 1, in <module>
    from .tobii import EyeTracker
ImportError: DLL load failed while importing tobii: Das angegebene Modul wurde nicht gefunden.
```

Could you help me to get it running?

Which Tobii Tracker are supported? Which Tobii SW and Versions are supported?
And how to get the license key?

**Comment by mh-salari** [comment]
Thank you for your interest in this software. It's specifically licensed for University of Eastern Finland (UEF) students taking the eye tracking course. If you're a UEF student in this course, please reach out to my university email to arrange a brief meeting. For others, I apologize that I can't provide further details. I appreciate your understanding.
